apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Threat-API-GITOPS
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/odonnkongolo/internal-developer-platform.git'
    targetRevision: main
    path: gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true