apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threat-api
  template:
    metadata:
      labels:
        app: threat-api
    spec:
      containers:
      - name: api
        # CRITICAL: We use the internal registry name k3s recognizes
        image: idp-registry:5111/threat-api:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: threat-api-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: threat-api
  ports:
  - port: 80
    targetPort: 8080